# Generated by Django 2.2.3 on 2019-08-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='dockerfile',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
