# Generated by Django 2.2.3 on 2019-08-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ATM_Block',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ATM_Branch',
            },
        ),
        migrations.CreateModel(
            name='ConfigDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
                'db_table': 'ATM_ConfigDetail',
            },
        ),
        migrations.CreateModel(
            name='ConfigType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ATM_ConfigType',
            },
        ),
        migrations.CreateModel(
            name='DLFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ATM_DLFramework',
            },
        ),
        migrations.CreateModel(
            name='OSType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ATM_OSType',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ATM_Project',
            },
        ),
        migrations.CreateModel(
            name='ConfigPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('config', models.ManyToManyField(blank=True, to='ConfigModel.ConfigDetail')),
            ],
            options={
                'verbose_name': 'Config Plan',
                'verbose_name_plural': 'Config Plan',
                'db_table': 'ATM_ConfigPlan',
            },
        ),
        migrations.AddField(
            model_name='configdetail',
            name='configtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConfigModel.ConfigType'),
        ),
    ]
