# Generated by Django 2.2.3 on 2019-08-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configdetail',
            options={'verbose_name': 'Config Option', 'verbose_name_plural': 'Config Option'},
        ),
        migrations.AlterField(
            model_name='configdetail',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='configplan',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='configtype',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
    ]
