# Generated by Django 2.2.3 on 2019-08-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BuildModel', '0001_initial'),
        ('ConfigModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ATM_Tag',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('precondition', models.TextField(blank=True, max_length=1000, null=True)),
                ('priority', models.SmallIntegerField(default=2)),
                ('tolerance', models.IntegerField(default=0)),
                ('timeout', models.IntegerField(default=0)),
                ('exectime', models.FloatField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ConfigModel.ConfigPlan')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Case',
                'db_table': 'ATM_TestCase',
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ATM_TestType',
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConfigModel.Branch')),
                ('dlframework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConfigModel.DLFramework')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConfigModel.Project')),
                ('runmode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BuildModel.RunMode')),
                ('testcase', models.ManyToManyField(blank=True, to='TestModel.TestCase')),
            ],
            options={
                'verbose_name': 'Test Plan',
                'verbose_name_plural': 'Test Plan',
                'db_table': 'ATM_TestPlan',
            },
        ),
        migrations.CreateModel(
            name='TestJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('buildplan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='BuildModel.BuildPlan')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='TestModel.TestJob')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='ConfigModel.Project')),
                ('testplan', models.ManyToManyField(blank=True, to='TestModel.TestPlan')),
            ],
            options={
                'verbose_name': 'Test Job',
                'verbose_name_plural': 'Test Job',
                'db_table': 'ATM_TestJob',
            },
        ),
        migrations.CreateModel(
            name='TestCmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cmdline', models.TextField(max_length=1000)),
                ('priority', models.SmallIntegerField(default=2)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConfigModel.Block')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConfigModel.Project')),
                ('tag', models.ManyToManyField(to='TestModel.Tag')),
                ('testtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TestModel.TestType')),
            ],
            options={
                'verbose_name': 'Command Lines',
                'verbose_name_plural': 'Command Lines',
                'db_table': 'ATM_TestCmd',
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='testcmd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TestModel.TestCmd'),
        ),
    ]
