# Generated by Django 2.2.3 on 2019-08-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigModel', '0002_auto_20190807_0753'),
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ConfigModel.ConfigPlan'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='exectime',
            field=models.FloatField(default=0, verbose_name='Execution Time'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcmd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TestModel.TestCmd', verbose_name='Commandline'),
        ),
        migrations.AlterField(
            model_name='testjob',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='TestModel.TestJob', verbose_name='Parent Job'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='dlframework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConfigModel.DLFramework', verbose_name='DL Framework'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='runmode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BuildModel.RunMode', verbose_name='Run Mode'),
        ),
    ]
