# Generated by Django 2.2.3 on 2019-08-22 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnvModel', '0001_initial'),
        ('TestModel', '0002_auto_20190807_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='env',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnvModel.DockerImage'),
        ),
    ]
