# Generated by Django 2.2.3 on 2019-08-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuildModel', '0002_auto_20190807_0753'),
        ('TestModel', '0003_testjob_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='runMode',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='BuildModel.RunMode'),
        ),
    ]
