# Generated by Django 2.2.3 on 2019-08-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_testjob_runmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
