# Generated by Django 2.2.3 on 2019-08-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20190823_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
