# Generated by Django 2.2.3 on 2019-10-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20190826_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='tolerance',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
