INSERT INTO `auth_permission` VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO `auth_permission` VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO `auth_permission` VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO `auth_permission` VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO `auth_permission` VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO `auth_permission` VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO `auth_permission` VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO `auth_permission` VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO `auth_permission` VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO `auth_permission` VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO `auth_permission` VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO `auth_permission` VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO `auth_permission` VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO `auth_permission` VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO `auth_permission` VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO `auth_permission` VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO `auth_permission` VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO `auth_permission` VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO `auth_permission` VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO `auth_permission` VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO `auth_permission` VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO `auth_permission` VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO `auth_permission` VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO `auth_permission` VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO `auth_permission` VALUES (25, 'Can add block', 7, 'add_block');
INSERT INTO `auth_permission` VALUES (26, 'Can change block', 7, 'change_block');
INSERT INTO `auth_permission` VALUES (27, 'Can delete block', 7, 'delete_block');
INSERT INTO `auth_permission` VALUES (28, 'Can view block', 7, 'view_block');
INSERT INTO `auth_permission` VALUES (29, 'Can add branch', 8, 'add_branch');
INSERT INTO `auth_permission` VALUES (30, 'Can change branch', 8, 'change_branch');
INSERT INTO `auth_permission` VALUES (31, 'Can delete branch', 8, 'delete_branch');
INSERT INTO `auth_permission` VALUES (32, 'Can view branch', 8, 'view_branch');
INSERT INTO `auth_permission` VALUES (33, 'Can add config', 9, 'add_config');
INSERT INTO `auth_permission` VALUES (34, 'Can change config', 9, 'change_config');
INSERT INTO `auth_permission` VALUES (35, 'Can delete config', 9, 'delete_config');
INSERT INTO `auth_permission` VALUES (36, 'Can view config', 9, 'view_config');
INSERT INTO `auth_permission` VALUES (37, 'Can add config detail', 10, 'add_configdetail');
INSERT INTO `auth_permission` VALUES (38, 'Can change config detail', 10, 'change_configdetail');
INSERT INTO `auth_permission` VALUES (39, 'Can delete config detail', 10, 'delete_configdetail');
INSERT INTO `auth_permission` VALUES (40, 'Can view config detail', 10, 'view_configdetail');
INSERT INTO `auth_permission` VALUES (41, 'Can add dl framework', 11, 'add_dlframework');
INSERT INTO `auth_permission` VALUES (42, 'Can change dl framework', 11, 'change_dlframework');
INSERT INTO `auth_permission` VALUES (43, 'Can delete dl framework', 11, 'delete_dlframework');
INSERT INTO `auth_permission` VALUES (44, 'Can view dl framework', 11, 'view_dlframework');
INSERT INTO `auth_permission` VALUES (45, 'Can add project', 12, 'add_project');
INSERT INTO `auth_permission` VALUES (46, 'Can change project', 12, 'change_project');
INSERT INTO `auth_permission` VALUES (47, 'Can delete project', 12, 'delete_project');
INSERT INTO `auth_permission` VALUES (48, 'Can view project', 12, 'view_project');
INSERT INTO `auth_permission` VALUES (49, 'Can add tag', 13, 'add_tag');
INSERT INTO `auth_permission` VALUES (50, 'Can change tag', 13, 'change_tag');
INSERT INTO `auth_permission` VALUES (51, 'Can delete tag', 13, 'delete_tag');
INSERT INTO `auth_permission` VALUES (52, 'Can view tag', 13, 'view_tag');
INSERT INTO `auth_permission` VALUES (53, 'Can add test case', 14, 'add_testcase');
INSERT INTO `auth_permission` VALUES (54, 'Can change test case', 14, 'change_testcase');
INSERT INTO `auth_permission` VALUES (55, 'Can delete test case', 14, 'delete_testcase');
INSERT INTO `auth_permission` VALUES (56, 'Can view test case', 14, 'view_testcase');
INSERT INTO `auth_permission` VALUES (57, 'Can add test type', 15, 'add_testtype');
INSERT INTO `auth_permission` VALUES (58, 'Can change test type', 15, 'change_testtype');
INSERT INTO `auth_permission` VALUES (59, 'Can delete test type', 15, 'delete_testtype');
INSERT INTO `auth_permission` VALUES (60, 'Can view test type', 15, 'view_testtype');
INSERT INTO `auth_permission` VALUES (61, 'Can add test plan', 16, 'add_testplan');
INSERT INTO `auth_permission` VALUES (62, 'Can change test plan', 16, 'change_testplan');
INSERT INTO `auth_permission` VALUES (63, 'Can delete test plan', 16, 'delete_testplan');
INSERT INTO `auth_permission` VALUES (64, 'Can view test plan', 16, 'view_testplan');
INSERT INTO `auth_permission` VALUES (65, 'Can add test job', 17, 'add_testjob');
INSERT INTO `auth_permission` VALUES (66, 'Can change test job', 17, 'change_testjob');
INSERT INTO `auth_permission` VALUES (67, 'Can delete test job', 17, 'delete_testjob');
INSERT INTO `auth_permission` VALUES (68, 'Can view test job', 17, 'view_testjob');
INSERT INTO `auth_permission` VALUES (69, 'Can add test cmd', 18, 'add_testcmd');
INSERT INTO `auth_permission` VALUES (70, 'Can change test cmd', 18, 'change_testcmd');
INSERT INTO `auth_permission` VALUES (71, 'Can delete test cmd', 18, 'delete_testcmd');
INSERT INTO `auth_permission` VALUES (72, 'Can view test cmd', 18, 'view_testcmd');
INSERT INTO `auth_permission` VALUES (73, 'Can add build combinations', 19, 'add_buildcombinations');
INSERT INTO `auth_permission` VALUES (74, 'Can change build combinations', 19, 'change_buildcombinations');
INSERT INTO `auth_permission` VALUES (75, 'Can delete build combinations', 19, 'delete_buildcombinations');
INSERT INTO `auth_permission` VALUES (76, 'Can view build combinations', 19, 'view_buildcombinations');
INSERT INTO `auth_permission` VALUES (77, 'Can add build dependency', 20, 'add_builddependency');
INSERT INTO `auth_permission` VALUES (78, 'Can change build dependency', 20, 'change_builddependency');
INSERT INTO `auth_permission` VALUES (79, 'Can delete build dependency', 20, 'delete_builddependency');
INSERT INTO `auth_permission` VALUES (80, 'Can view build dependency', 20, 'view_builddependency');
INSERT INTO `auth_permission` VALUES (81, 'Can add build detail', 21, 'add_builddetail');
INSERT INTO `auth_permission` VALUES (82, 'Can change build detail', 21, 'change_builddetail');
INSERT INTO `auth_permission` VALUES (83, 'Can delete build detail', 21, 'delete_builddetail');
INSERT INTO `auth_permission` VALUES (84, 'Can view build detail', 21, 'view_builddetail');
INSERT INTO `auth_permission` VALUES (85, 'Can add build mode', 22, 'add_buildmode');
INSERT INTO `auth_permission` VALUES (86, 'Can change build mode', 22, 'change_buildmode');
INSERT INTO `auth_permission` VALUES (87, 'Can delete build mode', 22, 'delete_buildmode');
INSERT INTO `auth_permission` VALUES (88, 'Can view build mode', 22, 'view_buildmode');
INSERT INTO `auth_permission` VALUES (89, 'Can add build plan', 23, 'add_buildplan');
INSERT INTO `auth_permission` VALUES (90, 'Can change build plan', 23, 'change_buildplan');
INSERT INTO `auth_permission` VALUES (91, 'Can delete build plan', 23, 'delete_buildplan');
INSERT INTO `auth_permission` VALUES (92, 'Can view build plan', 23, 'view_buildplan');
INSERT INTO `auth_permission` VALUES (93, 'Can add build project', 24, 'add_buildproject');
INSERT INTO `auth_permission` VALUES (94, 'Can change build project', 24, 'change_buildproject');
INSERT INTO `auth_permission` VALUES (95, 'Can delete build project', 24, 'delete_buildproject');
INSERT INTO `auth_permission` VALUES (96, 'Can view build project', 24, 'view_buildproject');
INSERT INTO `auth_permission` VALUES (97, 'Can add os type', 25, 'add_ostype');
INSERT INTO `auth_permission` VALUES (98, 'Can change os type', 25, 'change_ostype');
INSERT INTO `auth_permission` VALUES (99, 'Can delete os type', 25, 'delete_ostype');
INSERT INTO `auth_permission` VALUES (100, 'Can view os type', 25, 'view_ostype');
INSERT INTO `auth_permission` VALUES (101, 'Can add run mode', 26, 'add_runmode');
INSERT INTO `auth_permission` VALUES (102, 'Can change run mode', 26, 'change_runmode');
INSERT INTO `auth_permission` VALUES (103, 'Can delete run mode', 26, 'delete_runmode');
INSERT INTO `auth_permission` VALUES (104, 'Can view run mode', 26, 'view_runmode');
INSERT INTO `auth_permission` VALUES (105, 'Can add build info', 19, 'add_buildinfo');
INSERT INTO `auth_permission` VALUES (106, 'Can change build info', 19, 'change_buildinfo');
INSERT INTO `auth_permission` VALUES (107, 'Can delete build info', 19, 'delete_buildinfo');
INSERT INTO `auth_permission` VALUES (108, 'Can view build info', 19, 'view_buildinfo');
INSERT INTO `auth_permission` VALUES (109, 'Can add config type', 27, 'add_configtype');
INSERT INTO `auth_permission` VALUES (110, 'Can change config type', 27, 'change_configtype');
INSERT INTO `auth_permission` VALUES (111, 'Can delete config type', 27, 'delete_configtype');
INSERT INTO `auth_permission` VALUES (112, 'Can view config type', 27, 'view_configtype');
